[2024-12-06T23:38:44.612-0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T23:38:44.618-0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_dag.s3_upload manual__2024-12-07T05:38:37.768905+00:00 [queued]>
[2024-12-06T23:38:44.621-0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_dag.s3_upload manual__2024-12-07T05:38:37.768905+00:00 [queued]>
[2024-12-06T23:38:44.622-0600] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-06T23:38:44.631-0600] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-12-07 05:38:37.768905+00:00
[2024-12-06T23:38:44.634-0600] {standard_task_runner.py:72} INFO - Started process 18870 to run task
[2024-12-06T23:38:44.637-0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_dag', 's3_upload', 'manual__2024-12-07T05:38:37.768905+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpgnlqsilz']
[2024-12-06T23:38:44.637-0600] {standard_task_runner.py:105} INFO - Job 16: Subtask s3_upload
[2024-12-06T23:38:44.661-0600] {task_command.py:467} INFO - Running <TaskInstance: reddit_dag.s3_upload manual__2024-12-07T05:38:37.768905+00:00 [running]> on host m9dv9
[2024-12-06T23:38:44.697-0600] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Misael' AIRFLOW_CTX_DAG_ID='reddit_dag' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T05:38:37.768905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T05:38:37.768905+00:00'
[2024-12-06T23:38:44.698-0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-06T23:38:44.698-0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-06T23:38:44.698-0600] {logging_mixin.py:190} INFO - Current task name:s3_upload state:running start_date:2024-12-07 05:38:44.618858+00:00
[2024-12-06T23:38:44.698-0600] {logging_mixin.py:190} INFO - Dag name:reddit_dag and current dag run status:running
[2024-12-06T23:38:44.698-0600] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T23:38:44.704-0600] {logging_mixin.py:190} INFO - AioSession.__init__() got an unexpected keyword argument 'ann'
[2024-12-06T23:38:44.705-0600] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/dags/pipelines/upload_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/dags/etls/aws_etl.py", line 26, in upload_to_s3
    s3.put(file_path, bucket + '/raw/' + s3_file_name)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 565, in _put
    trailing_sep(rpath) or await self._isdir(rpath)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/s3fs/core.py", line 1498, in _isdir
    return bool(await self._lsdir(path))
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/s3fs/core.py", line 729, in _lsdir
    async for c in self._iterdir(
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/s3fs/core.py", line 760, in _iterdir
    await self.set_session()
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/s3fs/core.py", line 525, in set_session
    self.session = aiobotocore.session.AioSession(**self.kwargs)
TypeError: AioSession.__init__() got an unexpected keyword argument 'ann'
[2024-12-06T23:38:44.709-0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-06T23:38:44.710-0600] {logging_mixin.py:190} INFO - Task start:2024-12-07 05:38:44.618858+00:00 end:2024-12-07 05:38:44.709712+00:00 duration:0.090854
[2024-12-06T23:38:44.710-0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): s3_upload> dag:<DAG: reddit_dag> dagrun:<DagRun reddit_dag @ 2024-12-07 05:38:37.768905+00:00: manual__2024-12-07T05:38:37.768905+00:00, state:running, queued_at: 2024-12-07 05:38:37.781862+00:00. externally triggered: True>
[2024-12-06T23:38:44.710-0600] {logging_mixin.py:190} INFO - Failure caused by AioSession.__init__() got an unexpected keyword argument 'ann'
[2024-12-06T23:38:44.710-0600] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=reddit_dag, task_id=s3_upload, run_id=manual__2024-12-07T05:38:37.768905+00:00, execution_date=20241207T053837, start_date=20241207T053844, end_date=20241207T053844
[2024-12-06T23:38:44.716-0600] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T23:38:44.717-0600] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task s3_upload (AioSession.__init__() got an unexpected keyword argument 'ann'; 18870)
Traceback (most recent call last):
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/dags/pipelines/upload_s3_pipeline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/dags/etls/aws_etl.py", line 26, in upload_to_s3
    s3.put(file_path, bucket + '/raw/' + s3_file_name)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 565, in _put
    trailing_sep(rpath) or await self._isdir(rpath)
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/s3fs/core.py", line 1498, in _isdir
    return bool(await self._lsdir(path))
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/s3fs/core.py", line 729, in _lsdir
    async for c in self._iterdir(
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/s3fs/core.py", line 760, in _iterdir
    await self.set_session()
  File "/home/m9d9v9/PycharmProjects/Airflow-2/Airflow-2/.venv/lib/python3.10/site-packages/s3fs/core.py", line 525, in set_session
    self.session = aiobotocore.session.AioSession(**self.kwargs)
TypeError: AioSession.__init__() got an unexpected keyword argument 'ann'
[2024-12-06T23:38:44.729-0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T23:38:44.740-0600] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T23:38:44.741-0600] {local_task_job_runner.py:245} INFO - ::endgroup::
